#!/bin/bash

echo "🚀 Preparando aplicación para Vercel..."
echo ""

# Verificar que .env esté en .gitignore
if grep -q ".env" .gitignore; then
    echo "✅ .env está en .gitignore"
else
    echo "❌ ADVERTENCIA: .env NO está en .gitignore"
    echo "   Agregando .env a .gitignore..."
    echo ".env" >> .gitignore
fi

echo ""
echo "📋 Checklist de Despliegue:"
echo ""
echo "1. Variables de Entorno"
echo "   - ¿Tienes todas las variables del .env.example?"
echo "   - ¿Has configurado NEXTAUTH_SECRET?"
echo "   - ¿Has configurado las credenciales de Google OAuth?"
echo ""
echo "2. Git & GitHub"
echo "   - ¿Has creado un repositorio en GitHub?"
echo "   - ¿Has conectado tu repositorio local?"
echo ""
echo "3. Google OAuth"
echo "   - ¿Has agregado la URL de Vercel a las URLs autorizadas?"
echo ""
echo "4. Vercel"
echo "   - ¿Has creado una cuenta en Vercel?"
echo "   - ¿Has vinculado tu cuenta de GitHub?"
echo ""
echo "📝 Comandos para subir a GitHub:"
echo ""
echo "   git init"
echo "   git add ."
echo "   git commit -m \"Deploy to Vercel\""
echo "   git branch -M main"
echo "   git remote add origin https://github.com/TU-USUARIO/TU-REPO.git"
echo "   git push -u origin main"
echo ""
echo "🌐 Después de subir a GitHub:"
echo ""
echo "   1. Ve a https://vercel.com"
echo "   2. Click en 'Add New Project'"
echo "   3. Importa tu repositorio"
echo "   4. Configura las variables de entorno"
echo "   5. Click en 'Deploy'"
echo ""
echo "⚠️  IMPORTANTE:"
echo "   - Los usuarios y productos están en MEMORIA"
echo "   - Se perderán con cada despliegue"
echo "   - Considera usar MongoDB o PostgreSQL para producción"
echo ""
echo "📖 Lee DEPLOY.md para instrucciones detalladas"
echo ""
